name: Usando Secrets

on:
  workflow_dispatch:  # Solo manual, sin cron molesto

jobs:
  usar-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Usar API key secreta
      env:
        API_KEY: ${{ secrets.MI_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "API Key existe: ${API_KEY:+SÍ}"
        echo "Database URL existe: ${DATABASE_URL:+SÍ}"
        # NO se muestran los valores reales en logs
        
    - name: Ejemplo con Python
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python3 -c "
        import os
        api_key = os.environ.get('OPENAI_API_KEY')
        print(f'API Key cargada: {api_key[:8]}...' if api_key else 'No API key')
        "
